# Generated by Django 5.0.2 on 2024-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0002_remove_customuser_admin_remove_customuser_staff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_brush_time",
            field=models.IntegerField(default=0),
        ),
    ]
