# Generated by Django 5.0.2 on 2024-03-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_customuser_parent_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_pin_set",
            field=models.BooleanField(default=False),
        ),
    ]
