# Generated by Django 5.0.2 on 2024-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_customuser_is_pin_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_level",
            field=models.IntegerField(default=1),
        ),
    ]
