# Generated by Django 5.0.2 on 2024-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_customuser_current_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_level_max_xp",
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_level_xp",
            field=models.IntegerField(default=0),
        ),
    ]
