# Generated by Django 5.0.2 on 2024-03-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_customuser_current_level_max_xp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image_id",
            field=models.IntegerField(default=1),
        ),
    ]
