# Generated by Django 5.0.2 on 2024-04-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_customuser_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="max_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_brushes",
            field=models.IntegerField(default=0),
        ),
    ]
