# Generated by Django 5.0.2 on 2024-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0007_customuser_current_streak_customuser_max_streak_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
