# Generated by Django 5.0.2 on 2024-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_customuser_last_active_evening_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="percentage_evening",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="percentage_morning",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_brushes_evening",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_brushes_morning",
            field=models.IntegerField(default=0),
        ),
    ]
