# Generated by Django 5.0.2 on 2024-04-04 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_customuser_percentage_evening_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "activity_date"],
                        name="application_user_id_8be457_idx",
                    )
                ],
                "unique_together": {("user", "activity_date", "activity_type")},
            },
        ),
    ]
