# Generated by Django 5.0.2 on 2024-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_useractivity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useractivity",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="activity_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="useractivity",
            unique_together={
                ("user", "activity_date", "activity_time", "activity_type")
            },
        ),
    ]
