# Generated by Django 5.0.2 on 2024-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0012_alter_useractivity_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="percentage_evening",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="percentage_morning",
            field=models.FloatField(default=0.0),
        ),
    ]
