# Generated by Django 5.0.2 on 2024-04-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0013_alter_customuser_percentage_evening_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_brushes_days",
            field=models.IntegerField(default=0),
        ),
    ]
