# Generated by Django 5.0.2 on 2024-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0015_customuser_character_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_char_name_set",
            field=models.BooleanField(default=False),
        ),
    ]
